databases:
  - name: routealertdb
    databaseName: routealertdb
    user: routealertdb
    region: oregon
    plan: free

services:
    # Create a redis instance
  - type: redis
    name: sidekiq-redis
    region: oregon
    plan: free
    maxmemoryPolicy: noeviction
    ipAllowList: []

  # Let's create our background worker
  #- type: worker
  #  name: sidekiq-worker
  #  env: ruby
  #  region: oregon
  #  buildCommand: bundle install
  #  startCommand: bundle exec sidekiq
  #  autoDeploy: false
  #  envVars:
  #    - key: REDIS_URL
  #      fromService:
  #        type: redis
  #        name: sidekiq-redis
  #        property: connectionString

  - type: web
    name: routealert
    env: ruby
    region: oregon
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: routealertdb
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false